disabled clang build target due to error in upstream lib elog
[100%] Building CXX object src/CMakeFiles/midi2input.dir/midi2input.cpp.o In file included from
/home/travis/build/enetheru/midi2input/src/midi2input.cpp:27:# Please enter the commit message for your changes. Lines starting
/home/travis/build/enetheru/midi2input/src/elog/elog.h:15:12: error: # with '#' will be ignored, and an empty message aborts the
commit.
      binding of reference to type# On branch cmake
      'LOG::NullStream' to a value of# Your branch is up-to-date with 'origin/cmake'.
      type 'const LOG::NullStream' drops#
      qualifiers# Changes to be committed:
    return *this;# modified: .travis.yml
           ^~~~~# 1 error generated.# Untracked files: make[2]: *** [src/CMakeFiles/midi2input.dir/midi2input.cpp.o] Error 1# build/
make[1]: *** [src/CMakeFiles/midi2input.dir/all] Error 2# cmake/
make: *** [all] Error 2